#!/bin/sh

set -e

tmpfile=$(mktemp "${TMPDIR:-/tmp}/${0##*/}.XXXXXX")
trap 'rm -rf "$tmpfile"' EXIT INT TERM

if [ $# -ne 1 ]; then
    echo "Usage: ${0##*/} FILE_PATH" >&2
    exit 1
fi

filepath="$1"
if sourcepath=$(chezmoi source-path "$filepath" 2>/dev/null); then
    targetpath="$filepath"
elif targetpath=$(chezmoi target-path "$filepath" 2>/dev/null); then
    sourcepath="$filepath"
else
    echo >&2 "Error: unmanaged file: $filepath"
    exit 1
fi

if [ -f "$sourcepath" ]; then
    chezmoi decrypt "$sourcepath" >"$tmpfile" || {
        echo "Failed to decrypt $sourcepath" >&2
        exit 1
    }
else
    touch "$tmpfile"
fi
${VISUAL:-${EDITOR:-vi}} "$tmpfile"
chezmoi encrypt "$tmpfile" >"$sourcepath.new" || {
    rm -f "$sourcepath.new"
    echo "Failed to encrypt $sourcepath" >&2
    exit 1
}
mv "$sourcepath.new" "$sourcepath"
chezmoi apply "$targetpath"
