#!/usr/bin/env bash

dot_clean -m "$1"
find "$1" \( -name .DS_Store -o -name .apdisk \) -delete
if [ -d "$1/.Trashes" ]; then
    rm -rf "$1/.Trashes"
    touch "$1/.Trashes"
    chmod 000 "$1/.Trashes"
fi
if [ -d "$1/.fseventsd" ]; then
    rm -rf "$1/.fseventsd"
    touch "$1/.fseventsd"
    chmod 000 "$1/.fseventsd"
fi
rm -rf "$1/.TemporaryItems"
if [ -d "$1/.Spotlight-V100" ]; then
    mdutil -i off "$1"
    rm -rf "$1/.Spotlight-V100"
fi
hdiutil unmount "$1"
