#!/bin/sh


usage() {
    cat <<END >&2
${0##*/} [options..] URL [URL..]

Options:
  -v Increase verbosity
  -p PUP_ARGS
  -h   Show usage
END
    exit 2
}

verbose=0
detail=
pup_args=
while getopts vdp:h opt; do
    case "$opt" in
        v)
            verbose=$((verbose + 1))
            ;;
        d)
            detail=1
            ;;
        p)
            pup_args="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

# shellcheck disable=SC2086
for url; do
    http --follow --check-status --ignore-stdin "$url" | pup-links ${detail:+-d} "$url" $pup_args
done
