#!/bin/sh
# - Accept file paths on stdin
# - Accept the identifier command via command-line argument
# - Output files grouped by the identifier
#
# NOTE: Currently assumes the command will output '<id><TAB
# CHARACTER><filename>' lines

PATH=$(dirname "$0"):$PATH
TAB=$(printf '\t')

usage() {
    cat <<END >&2
${0##*/} [options..] [CMD [ARGS..]]

Options:
  -a   Also show non-duplicates
  -r   Reverse the expected order from <id> <fn> to <fn> <id>.
  -h   Show usage
END
    exit 2
}

all=0
reversed_order=0
while getopts arh opt; do
    case "$opt" in
        a)
            all=1
            ;;
        r)
            reversed_order=1
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

if echo "$*" | grep -q '{}'; then
    set -- -I"{}" "$@"
fi

remove_nondupes() {
    jdupes-oneline |
        sed -e "s/$TAB*$//" |
        grep "$TAB" |
        jdupes-multiline
}

if [ $# -gt 0 ]; then
    tr '\n' '\0' \
        | xargs -0 "$@"
else
    cat
fi |
    if [ $reversed_order -eq 1 ]; then
        grep -v "$TAB *$" |
        sort -t"$TAB" -k2 |
        group-by-column 2 "$TAB" |
        cut -d"$TAB" -f1
    else
        grep -v "^ *$TAB" |
        sort -t"$TAB" -k1 |
        group-by-column 1 "$TAB" |
        cut -d"$TAB" -f2-
    fi |
    if [ $all -eq 1 ]; then
        cat
    else
        remove_nondupes
    fi
