#!/usr/bin/env bash
# TODO:
#  - Consider separating the games within a given emulator where possible.
#    - DuckStation
#    - melonDS
#    - ScummVM
#    - RetroArch
#  - PCSX2 seems to use global memory card files, but split states, so
#  probably don't want to do it for that one.
#  - Dolphin: Uncertain, need to figure out what its files are.
#  - Figure out how restoring will work. Can I restore the latest of
#  everything, or the latest save for each tagged snapshot? If I only restore
#  the latest snapshot globally, it'll be whatever game was backed up most
#  recently, which wouldn't be what I'd want, so I might need
#  a ludusavi-restic-restore script too.

set -euo pipefail

config_file="${XDG_CONFIG_HOME:-$HOME/.config}/ludusavi-restic/config"
if [ ! -r "$config_file" ]; then
    echo >&2 "Missing configuration: $config_file"
    exit 1
fi
# shellcheck source=/dev/null
. "$config_file"

usage() {
    echo >&2 "${0##*/} [-g GAME] [-- RESTIC_ARGS..]"
    exit 2
}

game=
while getopts g:h opt; do
    case "$opt" in
        g)
            game="$OPTARG"
            ;;
        \? | h)
            usage
            ;;
    esac
done
shift $((OPTIND - 1))

ludusavi backup --api --preview ${game:+"$game"} | jq -r '.games |
  to_entries[] |
  "\(.key)\t\(.value.files | keys_unsorted | join("\t"))"
' |
    while IFS=$'\t' read -r game files; do
        printf '%s\t' "$files" | tr '\t' '\0' | restic backup --tag="$game" --files-from-raw=- --group-by host,tags "$@"
    done
