#!/bin/sh

usage() {
    echo >&2 "${0##*/} [-d] URL [PUP_ARGS..]"
    exit 2
}

detailed=0
while getopts dh opt; do
    case "$opt" in
    d)
        detailed=1
        ;;
    \? | h)
        usage
        ;;
    esac
done
shift $((OPTIND - 1))
if [ $# -lt 1 ]; then
    usage
fi

url="$1"
shift
if [ $# -eq 0 ]; then
    set -- a
fi

if [ $detailed -eq 1 ]; then
    pup "$@" 'json{}' |
        jq -r '.[] | [(.text | if type=="string" then gsub("^\\s+|\\s+$";"") | split("\n") | .[0] else . end), .href] | join("\t")' |
        while IFS=$(printf '\t') read -r text href; do
            href=$(urljoin "$url" "$href")
            printf '%s\t%s\n' "$href" "$text"
        done
else
    pup "$@" 'attr{href}' | tr '\n' '\0' | xargs -0 -n 1 urljoin "$url"
fi
