#!/usr/bin/env bash

if [ $# -eq 0 ]; then
    exit 0
fi

case "${OSTYPE:-}" in
    darwin*)
        stat_cmd=(stat -L -f '%i %d')
        ;;
    *)
        stat_cmd=(stat -Lc '%i %d')
        ;;
esac

read -r inode dev < <("${stat_cmd[@]}" -- "$1") || exit 1
shift

for p; do
    read -r i d < <("${stat_cmd[@]}" -- "$p") || exit 1
    if [ "$i" -ne "$inode" ] || [ "$d" -ne "$dev" ]; then
        exit 1
    fi
done
