#!/usr/bin/env -S uv run --script
#
# /// script
# requires-python = ">=3.8"
# dependencies = [
#     "emoji",
# ]
# ///

import emoji
import sys

try:
    sys.stdout.write(emoji.replace_emoji(sys.stdin.read(), replace=''))
except BrokenPipeError:
    sys.exit(1)
