#!/usr/bin/env python3

import sys
import urllib.parse

args = sys.argv[1:]
if args:
    for arg in args:
        print(urllib.parse.unquote(arg))
else:
    for line in sys.stdin:
        print(urllib.parse.unquote(line.rstrip('\n')))
