#!/usr/bin/env python3

import sys
import urllib.parse

args = sys.argv[1:]
if args:
    for arg in args:
        print(urllib.parse.quote(arg, safe=''))
else:
    for line in sys.stdin:
        print(urllib.parse.quote(line.rstrip('\n'), safe=''))
