#!/bin/sh

set_by_payee () {
    csvpycol -c Category 'next((category for pattern, category in zip(itertools.islice(args, 0, None, 2), itertools.islice(args, 1, None, 2)) if re.search(pattern, Payee)), Category)' "$@"
}

set_by_payee_and_category () {
    csvpycol -c Category 'next((category for pattern, catpattern, category in zip(itertools.islice(args, 0, None, 3), itertools.islice(args, 1, None, 3), itertools.islice(args, 2, None, 3)) if re.search(pattern, Payee) and re.search(catpattern, Category)), Category)' "$@"
}

set_by_payee_and_category_and_memo () {
    csvpycol -c Category 'next((category for pattern, catpattern, memopattern, category in zip(itertools.islice(args, 0, None, 4), itertools.islice(args, 1, None, 4), itertools.islice(args, 2, None, 4), itertools.islice(args, 3, None, 4)) if re.search(pattern, Payee) and re.search(catpattern, Category) and re.search(memopattern, Memo)), Category)' "$@"
}

rename_category () {
    csvpycol -c Category 'next((category for pattern, category in zip(itertools.islice(args, 0, None, 2), itertools.islice(args, 1, None, 2)) if re.search(pattern, Category)), Category)' "$@"
}

# Specify rules to split up my current Spending Money category for further
# analysis.
filter_dining="Chipotle|Khazana|Sweet Tomatoes|Schlotzsky|Popeye|Cheese Love|Dairy Queen|Wendy|Arby|Jack in the Box|Taco Bell|Blazin Barbeque|Sprinkles|Queso Good|Village Coffee|Culver|Chick-fil-A|Famous 48|Cracker Barrel|Snack Bar|Johnny Rockets|Krispy Kreme|Sweet Tomatoes|Starbucks|Applebee|Red Robin|Chili's|Butters|Gonutz|Barrio Queen|Khazana|Red Fire Cookery|Chipotle|Papa Murphy|Chick-Fil-A|Spoonz|Reef's Kitchen|Outback|Papa John|Buffalo Wild Wings|Caribou Coffee|Auntie Anne|Burger King|Hot Dogs|Raising Cane|KFC|TGI Friday|IHOP|Daily Dose Cafe|McDonald|Spaghetti Factory|Rusty Taco|Waffle Love|Menchie|In-N-Out|.*Cookies|Sweetwaters|.*Baking|.*Bake|kookies|NYPD Pizza|Churros Locos|Olive Garden|RoadHouse Cinemas|Nothing Bundt Cakes|Paris Baguette"
filter_entertainment="Fair|Ticketmaster|Fantasy Photo Booth|Museum|Comerica|Krazy Air|Mccormick Stillman|Macdonald's Ranch|Chuck.*Cheese|Ready Set Play|Sky Zone|Lego Discovery Center|Roblox|McCormick-Stillman Railroad Park|Fallout Games|Macayo|Roadhouse|Cub Scouts|Mavrix|Slick City Chandler"
filter_furniture='Ikea|Tuft|Sleep Number|Whimsie'
filter_gas="Holiday|Circle K|Costco.*Gas|Fry's Fuel|QuikTrip|Motley BP|Walmart Fuel|Sam.*Club Fuel"
filter_pets='Petco|PetSmart|Petsmart|D Pet Hotels|Spaw on the Spot'
filter_grocery="Bashas|Albertson|Girl Scouts|Safeway"
filter_clothing="Old Navy|Gap|Kohl's$|Famous Footwear|Burlington|T.J. Maxx|J.*Crew|Banana Republic|Children.*Place"

cat "$@" \
    | rename_category \
        "Hidden Categories: Bras$" "Spending: Spending Money" \
        "Spending: Village Coffee" "Spending: Spending Money" \
        "Spending: Bills" "Obligations: Bills" \
        "Hidden Categories: Veterinary" "Contingencies: Veterinary" \
        "Hidden Categories: Medical & Dental" "Contingencies: Medical & Dental" \
        "Spending: Allowance" "Obligations: Allowance" \
    | set_by_payee \
        "$filter_dining" "Spending: Dining" \
        "$filter_entertainment" "Spending: Entertainment" \
        "$filter_furniture" "Spending: Furnishings" \
        "$filter_gas" "Spending: Gas" \
        "$filter_pets" "Spending: Pets" \
        "$filter_grocery" "Spending: Groceries" \
        "$filter_clothing" "Spending: Clothing" \
        "Right Honda" "Spending: Auto Furnishing" \
        "Barnes.*Noble" "Spending: Books" \
        "Great Wolf" "Future: Gifts" \
        \
        "Dorian Studio" "Spending: Photography" \
        \
        "Badger Creek" "Spending: Personal Care" \
        "Ulta" "Spending: Personal Care" \
        \
        "Home Depot" "Spending: Household Supplies" \
        "Scheels" "Spending: Household Supplies" \
        "Hobby Lobby" "Spending: Household Supplies" \
        "Five Below" "Spending: Household Supplies" \
        "Dollar Tree" "Spending: Household Supplies" \
        "Michaels" "Spending: Household Supplies" \
        \
        "BuyTheYearBook.com" "Spending: School" \
        \
        "Pharmacy" "Spending: Pharmacy" \
        \
        "Parallels" "Future Obligations: Future Bills" \
        \
        "M&T Mortgage" "Rental Property: Townhouse: Rental Bills" \
        "M&T Bank" "Rental Property: Townhouse: Rental Bills" \
        "Maplebrook Estates" "Rental Property: Townhouse: Rental Bills" \
        "Legalzoom" "Rental Property: Townhouse: Rental Future Bills" \
        "Tom’s Custom Window" "Rental Property: Townhouse: Rental Maintenance" \
        "Sunrise" "Rental Property: Trailer: Rental Bills" \
        "Berkeley Electric" "Rental Property: Trailer: Rental Bills" \
        "Berkeley County" "Rental Property: Trailer: Rental Future Bills" \
        \
        "Picture People" "Future Obligations: Future Bills" \
        \
        "Hiya Health" "Spending: Subscription: Hiya" \
        "Llama Naturals" "Spending: Subscription: Llama Naturals" \
        \
        "Party Jungle" "Subscriptions: Entertainment: Party Jungle" \
    \
    | set_by_payee_and_category \
        "Anthony Meyers" "Inflow: Ready to Assign|To be Budgeted|Bills" "Rental Property: Townhouse: Rental Income" \
        "Alexa Meyers" "Inflow: Ready to Assign|To be Budgeted|Bills" "Rental Property: Townhouse: Rental Income" \
        "Anthony Meyers" "Rental Property Expenses" "Rental Property: Townhouse: Rental Maintenance" \
        "Alexa Meyers" "Rental Property Expenses" "Rental Property: Townhouse: Rental Maintenance" \
        "Shutterfly" "Future: Christmas Gifts" "Future: Future Bills" \
        \
        "APS" "Obligations: Bills" "Bills: Electric" \
        "Honda Financial" "Obligations: Bills" "Bills: Car Payment" \
        "Verizon" "Obligations: Bills" "Bills: Cellular" \
        "State Farm" "Obligations: Bills" "Bills: Insurance" \
        "AppFolio" "Obligations: Bills" "Bills: Rent" \
        "Realty Executives" "Obligations: Bills" "Bills: Rent" \
        "Cox" "Obligations: Bills" "Bills: Internet" \
        "City of Scottsdale" "Obligations: Bills" "Bills: Water & Sewer" \
        "Public Storage" "Obligations: Bills" "Bills: Storage Unit" \
        \
        "AirVPN" "Obligations: Bills" "Subscriptions: VPN" \
        \
        "State Farm" "Future Obligations: Rental Insurance" "Future Bills: Rental Insurance" \
        \
        "Microsoft" "Spending: Spending Money" "Spending: Entertainment" \
        \
        "Bath & Body Works" "Spending: Spending Money" "Spending: Household Supplies" \
    | set_by_payee_and_category_and_memo \
        "Apple Store" "Obligations: Bills" "Nikki's Watch Financing" "Device Upgrades: Nikki's Watch" \
        "Apple Store" "Obligations: Bills" "Matthew's Watch Financing" "Device Upgrades: Matthew's Watch" \
        "Apple Store" "Obligations: Bills" "Chris' Watch Financing" "Device Upgrades: Chris' Watch" \
        \
        "Apple Services" "Obligations: Bills" "AppleCare" "Bills: AppleCare" \
    | cat
